on: 
  workflow_dispatch:
  push:

jobs:
  rebuild_droplet_job:
    runs-on: ubuntu-latest
    name: Rebuild Digital Ocean Droplet
    steps:
    - name: Trigger droplet rebuild & wait for completion
      uses: chrisjsimpson/droplet-rebuild-action@v0.4
      with:
        digital-ocean-access-token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
        droplet-id: ${{ secrets.DROPLET_ID }}
        image: ${{ secrets.IMAGE }}
